services:

  nginx:
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./nginx/http-local.conf:/etc/nginx/http-listen.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

  app-blue:
    image: warcraft3sounds:local
    volumes:
      - ${SOUNDS_HOST_DIR:-../public/sounds}:/root/warcraft3sounds/sounds:ro

  app-green:
    image: warcraft3sounds:local
    volumes:
      - ${SOUNDS_HOST_DIR:-../public/sounds}:/root/warcraft3sounds/sounds:ro
